[package]
name = "crosspmv"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0.98"
crossterm = "0.29.0"
ignore = "0.4.23"
inquire = "0.7.5"
serde_json = { version = "1.0.140", features = ["preserve_order"] }
toml_edit = "0.22.26"
