[package]
name = "crosspmv"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
clap_complete = "4.5.50"
clap_complete_nushell = "4.5.5"
ignore = "0.4.23"
serde_json = { version = "1.0.140", features = ["preserve_order"] }
toml_edit = "0.22.26"
